// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package com.nfqsolutions.jpalm;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PalmMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jpalm.PalmMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string pipeline = 1;</code>
     */
    java.lang.String getPipeline();
    /**
     * <code>string pipeline = 1;</code>
     */
    com.google.protobuf.ByteString
        getPipelineBytes();

    /**
     * <code>string client = 2;</code>
     */
    java.lang.String getClient();
    /**
     * <code>string client = 2;</code>
     */
    com.google.protobuf.ByteString
        getClientBytes();

    /**
     * <code>int64 stage = 3;</code>
     */
    long getStage();

    /**
     * <code>string function = 4;</code>
     */
    java.lang.String getFunction();
    /**
     * <code>string function = 4;</code>
     */
    com.google.protobuf.ByteString
        getFunctionBytes();

    /**
     * <code>string cache = 5;</code>
     */
    java.lang.String getCache();
    /**
     * <code>string cache = 5;</code>
     */
    com.google.protobuf.ByteString
        getCacheBytes();

    /**
     * <code>bytes payload = 6;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code jpalm.PalmMessage}
   */
  public  static final class PalmMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jpalm.PalmMessage)
      PalmMessageOrBuilder {
    // Use PalmMessage.newBuilder() to construct.
    private PalmMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PalmMessage() {
      pipeline_ = "";
      client_ = "";
      stage_ = 0L;
      function_ = "";
      cache_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PalmMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              pipeline_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              client_ = s;
              break;
            }
            case 24: {

              stage_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              function_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              cache_ = s;
              break;
            }
            case 50: {

              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nfqsolutions.jpalm.Messages.internal_static_jpalm_PalmMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nfqsolutions.jpalm.Messages.internal_static_jpalm_PalmMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nfqsolutions.jpalm.Messages.PalmMessage.class, com.nfqsolutions.jpalm.Messages.PalmMessage.Builder.class);
    }

    public static final int PIPELINE_FIELD_NUMBER = 1;
    private volatile java.lang.Object pipeline_;
    /**
     * <code>string pipeline = 1;</code>
     */
    public java.lang.String getPipeline() {
      java.lang.Object ref = pipeline_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pipeline_ = s;
        return s;
      }
    }
    /**
     * <code>string pipeline = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPipelineBytes() {
      java.lang.Object ref = pipeline_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pipeline_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object client_;
    /**
     * <code>string client = 2;</code>
     */
    public java.lang.String getClient() {
      java.lang.Object ref = client_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        client_ = s;
        return s;
      }
    }
    /**
     * <code>string client = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientBytes() {
      java.lang.Object ref = client_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        client_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STAGE_FIELD_NUMBER = 3;
    private long stage_;
    /**
     * <code>int64 stage = 3;</code>
     */
    public long getStage() {
      return stage_;
    }

    public static final int FUNCTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object function_;
    /**
     * <code>string function = 4;</code>
     */
    public java.lang.String getFunction() {
      java.lang.Object ref = function_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        function_ = s;
        return s;
      }
    }
    /**
     * <code>string function = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFunctionBytes() {
      java.lang.Object ref = function_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        function_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CACHE_FIELD_NUMBER = 5;
    private volatile java.lang.Object cache_;
    /**
     * <code>string cache = 5;</code>
     */
    public java.lang.String getCache() {
      java.lang.Object ref = cache_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cache_ = s;
        return s;
      }
    }
    /**
     * <code>string cache = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCacheBytes() {
      java.lang.Object ref = cache_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cache_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 6;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPipelineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pipeline_);
      }
      if (!getClientBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, client_);
      }
      if (stage_ != 0L) {
        output.writeInt64(3, stage_);
      }
      if (!getFunctionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, function_);
      }
      if (!getCacheBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cache_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(6, payload_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPipelineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pipeline_);
      }
      if (!getClientBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, client_);
      }
      if (stage_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, stage_);
      }
      if (!getFunctionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, function_);
      }
      if (!getCacheBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cache_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, payload_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nfqsolutions.jpalm.Messages.PalmMessage)) {
        return super.equals(obj);
      }
      com.nfqsolutions.jpalm.Messages.PalmMessage other = (com.nfqsolutions.jpalm.Messages.PalmMessage) obj;

      boolean result = true;
      result = result && getPipeline()
          .equals(other.getPipeline());
      result = result && getClient()
          .equals(other.getClient());
      result = result && (getStage()
          == other.getStage());
      result = result && getFunction()
          .equals(other.getFunction());
      result = result && getCache()
          .equals(other.getCache());
      result = result && getPayload()
          .equals(other.getPayload());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PIPELINE_FIELD_NUMBER;
      hash = (53 * hash) + getPipeline().hashCode();
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
      hash = (37 * hash) + STAGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStage());
      hash = (37 * hash) + FUNCTION_FIELD_NUMBER;
      hash = (53 * hash) + getFunction().hashCode();
      hash = (37 * hash) + CACHE_FIELD_NUMBER;
      hash = (53 * hash) + getCache().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nfqsolutions.jpalm.Messages.PalmMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nfqsolutions.jpalm.Messages.PalmMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jpalm.PalmMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jpalm.PalmMessage)
        com.nfqsolutions.jpalm.Messages.PalmMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nfqsolutions.jpalm.Messages.internal_static_jpalm_PalmMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nfqsolutions.jpalm.Messages.internal_static_jpalm_PalmMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nfqsolutions.jpalm.Messages.PalmMessage.class, com.nfqsolutions.jpalm.Messages.PalmMessage.Builder.class);
      }

      // Construct using com.nfqsolutions.jpalm.Messages.PalmMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pipeline_ = "";

        client_ = "";

        stage_ = 0L;

        function_ = "";

        cache_ = "";

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nfqsolutions.jpalm.Messages.internal_static_jpalm_PalmMessage_descriptor;
      }

      public com.nfqsolutions.jpalm.Messages.PalmMessage getDefaultInstanceForType() {
        return com.nfqsolutions.jpalm.Messages.PalmMessage.getDefaultInstance();
      }

      public com.nfqsolutions.jpalm.Messages.PalmMessage build() {
        com.nfqsolutions.jpalm.Messages.PalmMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nfqsolutions.jpalm.Messages.PalmMessage buildPartial() {
        com.nfqsolutions.jpalm.Messages.PalmMessage result = new com.nfqsolutions.jpalm.Messages.PalmMessage(this);
        result.pipeline_ = pipeline_;
        result.client_ = client_;
        result.stage_ = stage_;
        result.function_ = function_;
        result.cache_ = cache_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nfqsolutions.jpalm.Messages.PalmMessage) {
          return mergeFrom((com.nfqsolutions.jpalm.Messages.PalmMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nfqsolutions.jpalm.Messages.PalmMessage other) {
        if (other == com.nfqsolutions.jpalm.Messages.PalmMessage.getDefaultInstance()) return this;
        if (!other.getPipeline().isEmpty()) {
          pipeline_ = other.pipeline_;
          onChanged();
        }
        if (!other.getClient().isEmpty()) {
          client_ = other.client_;
          onChanged();
        }
        if (other.getStage() != 0L) {
          setStage(other.getStage());
        }
        if (!other.getFunction().isEmpty()) {
          function_ = other.function_;
          onChanged();
        }
        if (!other.getCache().isEmpty()) {
          cache_ = other.cache_;
          onChanged();
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nfqsolutions.jpalm.Messages.PalmMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nfqsolutions.jpalm.Messages.PalmMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object pipeline_ = "";
      /**
       * <code>string pipeline = 1;</code>
       */
      public java.lang.String getPipeline() {
        java.lang.Object ref = pipeline_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pipeline_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string pipeline = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPipelineBytes() {
        java.lang.Object ref = pipeline_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pipeline_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pipeline = 1;</code>
       */
      public Builder setPipeline(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pipeline_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string pipeline = 1;</code>
       */
      public Builder clearPipeline() {
        
        pipeline_ = getDefaultInstance().getPipeline();
        onChanged();
        return this;
      }
      /**
       * <code>string pipeline = 1;</code>
       */
      public Builder setPipelineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pipeline_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object client_ = "";
      /**
       * <code>string client = 2;</code>
       */
      public java.lang.String getClient() {
        java.lang.Object ref = client_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          client_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClientBytes() {
        java.lang.Object ref = client_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          client_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client = 2;</code>
       */
      public Builder setClient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        client_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client = 2;</code>
       */
      public Builder clearClient() {
        
        client_ = getDefaultInstance().getClient();
        onChanged();
        return this;
      }
      /**
       * <code>string client = 2;</code>
       */
      public Builder setClientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        client_ = value;
        onChanged();
        return this;
      }

      private long stage_ ;
      /**
       * <code>int64 stage = 3;</code>
       */
      public long getStage() {
        return stage_;
      }
      /**
       * <code>int64 stage = 3;</code>
       */
      public Builder setStage(long value) {
        
        stage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 stage = 3;</code>
       */
      public Builder clearStage() {
        
        stage_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object function_ = "";
      /**
       * <code>string function = 4;</code>
       */
      public java.lang.String getFunction() {
        java.lang.Object ref = function_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          function_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string function = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFunctionBytes() {
        java.lang.Object ref = function_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          function_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string function = 4;</code>
       */
      public Builder setFunction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        function_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string function = 4;</code>
       */
      public Builder clearFunction() {
        
        function_ = getDefaultInstance().getFunction();
        onChanged();
        return this;
      }
      /**
       * <code>string function = 4;</code>
       */
      public Builder setFunctionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        function_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cache_ = "";
      /**
       * <code>string cache = 5;</code>
       */
      public java.lang.String getCache() {
        java.lang.Object ref = cache_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cache_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cache = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCacheBytes() {
        java.lang.Object ref = cache_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cache_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cache = 5;</code>
       */
      public Builder setCache(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cache_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cache = 5;</code>
       */
      public Builder clearCache() {
        
        cache_ = getDefaultInstance().getCache();
        onChanged();
        return this;
      }
      /**
       * <code>string cache = 5;</code>
       */
      public Builder setCacheBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cache_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 6;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 6;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 6;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:jpalm.PalmMessage)
    }

    // @@protoc_insertion_point(class_scope:jpalm.PalmMessage)
    private static final com.nfqsolutions.jpalm.Messages.PalmMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nfqsolutions.jpalm.Messages.PalmMessage();
    }

    public static com.nfqsolutions.jpalm.Messages.PalmMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PalmMessage>
        PARSER = new com.google.protobuf.AbstractParser<PalmMessage>() {
      public PalmMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PalmMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PalmMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PalmMessage> getParserForType() {
      return PARSER;
    }

    public com.nfqsolutions.jpalm.Messages.PalmMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jpalm_PalmMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jpalm_PalmMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\005jpalm\"p\n\013PalmMessage\022\020" +
      "\n\010pipeline\030\001 \001(\t\022\016\n\006client\030\002 \001(\t\022\r\n\005stag" +
      "e\030\003 \001(\003\022\020\n\010function\030\004 \001(\t\022\r\n\005cache\030\005 \001(\t" +
      "\022\017\n\007payload\030\006 \001(\014B\"\n\026com.nfqsolutions.jp" +
      "almB\010Messagesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_jpalm_PalmMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jpalm_PalmMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jpalm_PalmMessage_descriptor,
        new java.lang.String[] { "Pipeline", "Client", "Stage", "Function", "Cache", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
